[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wolta"
authors = [{name = "Sadık Efe Kartav", email = "sadikefe69@gmail.com"}]
dynamic = ["version", "description"]
